[[profile]]
name = "desktop"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    enable = true
    search = ["m=27GL850", "s=005NTZN7V717", "v=LG Electronics"]
    mode = { width = 2560, height = 1440, refresh = 144}
    position = { x = 1200, y = 550 }
    scale = 1.2

    [[profile.output]]
    enable = true
    search = ["m=DELL U2715H", "s=H7YCC6B806JS", "v=Dell Inc."]
    mode = { width = 2560, height = 1440, refresh = 60}
    position = { x = 0, y = 0 }
    transform = "90"
    scale = 1.2 
